# Generated by Django 6.0.1 on 2026-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
