# Generated by Django 6.0.1 on 2026-07-25 12:32

import users.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.user.CustomUserManager()),
            ],
        ),
    ]
