# Generated by Django 6.0.1 on 2026-07-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_initial"),
        ("events", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accepted_terms",
            field=models.ForeignKey(
                blank=True,
                help_text="The terms version the customer accepted at checkout.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_acceptances",
                to="data_management.termsandconditions",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(
                blank=True,
                help_text="The customer's email, captured at checkout (claim).",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_first_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The customer's first name.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_last_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The customer's last name.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="The Stripe Customer ID for this order's buyer.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the customer accepted the terms during checkout.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Deprecated: customer orders no longer create a user. Retained until the guest-User removal migration drops it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
