# Generated by Django 6.0.1 on 2026-07-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_backfill_customer_from_guest"),
        ("partners", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="referred_by_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="The partner who referred this order via discount code.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_orders",
                to="partners.partner",
            ),
        ),
    ]
