# Generated by Django 6.0.1 on 2026-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_backfill_referred_by_partner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
