# Generated by Django 6.0.1 on 2026-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_event_reference_and_florist_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Geocoded latitude of the recipient address. Null means the address has not been geocoded, and the order cannot be matched to a florist.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Geocoded longitude of the recipient address. Null means the address has not been geocoded, and the order cannot be matched to a florist.",
                null=True,
            ),
        ),
    ]
