# Generated by Django 6.0.1 on 2026-08-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_order_latitude_order_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="commission_amount",
        ),
    ]
