# Generated by Django 6.0.1 on 2026-08-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_remove_event_commission_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("claimed", "Claimed"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                help_text="Lifecycle of the delivery. 'scheduled' means paid for and on the claim board; 'claimed' means a florist has taken it. Replaces the old 'ordered', which described Bloomprint ordering flowers by hand — the florist does that now.",
                max_length=20,
            ),
        ),
    ]
