# Generated by Django 6.0.1 on 2026-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient_email",
            field=models.EmailField(
                blank=True,
                help_text="Direct email target for customer notifications (no user row).",
                max_length=254,
                null=True,
            ),
        ),
    ]
