# Generated by Django 6.0.1 on 2026-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0004_notification_recipient_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient_user",
        ),
    ]
