# Generated by Django 6.0.1 on 2026-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0004_notification_recipient_email"),
        # The backfill reads Notification.recipient_user, so it must run before
        # this removal regardless of cross-app migration ordering.
        ("events", "0005_backfill_customer_from_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient_user",
        ),
    ]
