# Generated by Django 6.0.1 on 2026-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0006_business_account_notification_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient_email",
            field=models.EmailField(
                blank=True,
                help_text="Direct email target where there is no account to resolve — customer notifications and florist outreach.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("business_account", "Business account"),
                    ("customer", "Customer"),
                    ("florist_prospect", "Florist prospect"),
                ],
                max_length=20,
            ),
        ),
    ]
