# Generated by Django 6.0.1 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_alter_notification_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('business_account', 'Business account'),
                    ('customer', 'Customer'),
                    ('manual', 'Manual email'),
                    ('florist_prospect', 'Florist prospect'),
                ],
                max_length=20,
            ),
        ),
    ]
