# Generated by Django 6.0.1 on 2026-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_alter_discountusage_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountusage",
            name="user",
        ),
    ]
