# Generated by Django 6.0.1 on 2026-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_business_account_domain_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryrequest",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="deliveryrequest",
            name="first_notified_at",
        ),
        migrations.RemoveField(
            model_name="deliveryrequest",
            name="second_notified_at",
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="status",
            field=models.CharField(
                choices=[("accepted", "Accepted")], default="accepted", max_length=20
            ),
        ),
    ]
