# Generated by Django 6.0.1 on 2026-08-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0007_remove_deliveryrequest_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="currency",
            field=models.CharField(default="AUD", max_length=3),
        ),
    ]
