# Generated by Django 6.0.1 on 2026-08-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_alter_payout_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryrequest",
            name="token",
        ),
    ]
