# Generated by Django 6.0.1 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_remove_deliveryrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='bsb',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
