"""
Django settings for bloomprint project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY")

# No STRIPE_PUBLISHABLE_KEY here: the publishable key is only ever used by the
# browser, and Next.js inlines it from NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY at
# build time. Django never needs it.
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

SITE_URL = os.environ.get("SITE_URL")
HASHING_SALT = os.environ.get("HASHING_SALT")
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL")
ADMIN_NUMBER = os.environ.get("ADMIN_NUMBER")
MIN_DAYS_BEFORE_CREATE = 3
MIN_DAYS_BEFORE_EDIT = 7
SUBSCRIPTION_CHARGE_LEAD_DAYS = 7
MIN_BUDGET = 65
DELIVERY_INCLUDED_THRESHOLD = 65
DELIVERY_FEE = 20

# Bloom Print's cut of the bouquet budget. The delivery fee is not commissioned —
# it passes to the florist in full. Quoted to florists as a flat 10%.
# Changing this only affects new orders: Order reprices while pending_payment
# only, and Event snapshots the florist's figures at creation.
FLORIST_COMMISSION_RATE = os.environ.get("FLORIST_COMMISSION_RATE", "0.10")

# Where the florist-brief QR code sends a florist who scans it. An unclaimed
# delivery points at the signup page, since the reader may not have an account;
# a claimed one points at login, since they certainly do.
FLORIST_SIGNUP_URL = os.environ.get(
    "FLORIST_SIGNUP_URL", "https://www.bloomprint.com.au/florists"
)
FLORIST_LOGIN_URL = os.environ.get(
    "FLORIST_LOGIN_URL", "https://www.bloomprint.com.au/login"
)

DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = ['ethanbetts.pythonanywhere.com', 'api.bloomprint.com.au', 'www.bloomprint.com.au', '127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = ['https://www.bloomprint.com.au', 
                        'https://api.bloomprint.com.au'
                        ]

if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:5173',
    ])

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "rest_framework",
    "rest_framework_simplejwt",
    "users",
    "events",
    "payments",
    "data_management",
    "partners",
    "marketing",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'frontend', 'dist')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'bloomprint_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend', 'dist'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

AUTH_COOKIE = 'access_token'
AUTH_COOKIE_REFRESH = 'refresh_token'
GUEST_CHECKOUT_LIFETIME = timedelta(days=7)
MAGIC_LINK_LIFETIME = timedelta(minutes=30)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/hour',
        'user': '500/hour'
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY")
MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN")
DEFAULT_FROM_EMAIL = "Bloom Print <postmaster@mail.bloomprint.com.au>"

TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID")

INTERNAL_API_KEY    = os.environ.get("INTERNAL_API_KEY")
MARKETING_SERVER_URL = os.environ.get("MARKETING_SERVER_URL", "https://www.bloomprint.com.au")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER")
TWILIO_MESSAGING_SERVICE_SID = os.environ.get("TWILIO_MESSAGING_SERVICE_SID")
