'use client';

import { useRouter } from 'next/navigation'; import { Search } from 'lucide-react'; import { getAdminCommissions } from '@/api/admin'; import { DASHBOARD_STATUS_STYLES } from '@/components/dashboard/DashboardData';
import DashboardDataTable, { DashboardFilterSelect, DashboardTableStatusPill, formatDashboardTableDate, type DashboardColumn } from '@/components/dashboard/DashboardDataTable'; import { useDashboardTableQuery } from '@/components/dashboard/useDashboardTableQuery'; import { usePaginatedDashboardData } from '@/components/dashboard/usePaginatedDashboardData';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import type { AdminCommission } from '@/types/AdminCommission';

const PAGE_SIZE = 50; const STATUS_ORDER = ['pending', 'approved', 'processing', 'paid', 'denied'];
const STATUS_OPTIONS = [{ value: 'all', label: 'All statuses' }, ...STATUS_ORDER.map((status) => ({ value: status, label: DASHBOARD_STATUS_STYLES[status].label }))]; const TYPE_OPTIONS = [{ value: 'all', label: 'All types' }, { value: 'referral', label: 'Referral' }, { value: 'fulfillment', label: 'Fulfillment' }];
const accountName = (item: AdminCommission) => item.business_account_name || `Account #${item.business_account_id ?? '—'}`;

export default function AdminPayoutListPage() {
  const router = useRouter(); const table = useDashboardTableQuery(); const { data, loading, error } = usePaginatedDashboardData(getAdminCommissions, { status: table.status, type: table.kind, search: table.search, ordering: table.ordering, page: table.page, pageSize: PAGE_SIZE });
  const columns: DashboardColumn<AdminCommission>[] = [
    { key: 'account', header: 'Account', sortable: true, render: (item) => <span className="font-medium text-slate-900">{accountName(item)}</span> },
    { key: 'type', header: 'Type', sortable: true, cellClassName: 'text-slate-700', render: (item) => item.commission_type === 'fulfillment' ? 'Fulfillment' : 'Referral' },
    { key: 'amount', header: 'Amount', sortable: true, align: 'right', cellClassName: 'font-semibold text-slate-950', render: (item) => `$${Number(item.amount).toFixed(2)}` },
    { key: 'status', header: 'Status', sortable: true, render: (item) => <DashboardTableStatusPill className={DASHBOARD_STATUS_STYLES[item.status]?.pill}>{DASHBOARD_STATUS_STYLES[item.status]?.label ?? item.status}</DashboardTableStatusPill> },
    { key: 'event', header: 'Event', cellClassName: 'font-mono text-sm text-slate-600', render: (item) => item.event ? `#${item.event}` : '—' },
    { key: 'created_at', header: 'Created', sortable: true, cellClassName: 'text-sm text-slate-600', render: (item) => formatDashboardTableDate(item.created_at) },
  ]; const pageCount = Math.max(1, Math.ceil(data.count / PAGE_SIZE));
  return <>{error && <p className="px-4 pt-4 text-sm text-red-600 md:px-6">{error}</p>}<DashboardDataTable title="Payouts" filterSummary={`${data.count.toLocaleString('en-AU')} ${data.count === 1 ? 'payout' : 'payouts'} matching this view`} filters={<><DashboardFilterSelect value={table.status} onValueChange={table.setStatus} options={STATUS_OPTIONS} ariaLabel="Filter payouts by status" /><DashboardFilterSelect value={table.kind} onValueChange={table.setKind} options={TYPE_OPTIONS} ariaLabel="Filter payouts by type" /><form onSubmit={(event) => { event.preventDefault(); table.submitSearch(); }}><div className="flex gap-2"><Input value={table.query} onChange={(event) => table.setQuery(event.target.value)} placeholder="Search account, event or note" aria-label="Search payouts" className="border-slate-300 bg-white text-slate-900" /><Button type="submit" variant="outline"><Search className="mr-1.5 h-4 w-4" /> Search</Button></div></form></>} legend={<><span className="font-medium text-slate-600">Row colour:</span>{STATUS_ORDER.map((status) => <span key={status} className="inline-flex items-center gap-1.5"><span className={`h-3 w-3 rounded-sm ${DASHBOARD_STATUS_STYLES[status].swatch}`} />{DASHBOARD_STATUS_STYLES[status].label}</span>)}</>} showClear={table.isDirty} onClearFilters={table.clear} columns={columns} rows={data.results} rowKey={(item) => item.id} loading={loading} emptyMessage="No payouts match these filters." sort={table.sort} onSort={table.toggleSort} onRowClick={(item) => router.push(`/dashboard/admin/payouts/${item.id}`)} rowClassName={(item) => DASHBOARD_STATUS_STYLES[item.status]?.row ?? 'hover:bg-slate-50'} pagination={{ page: table.page, pageCount, total: data.count, pageSize: PAGE_SIZE, hasPrev: Boolean(data.previous), hasNext: Boolean(data.next), onPrev: () => table.setPage((value) => value - 1), onNext: () => table.setPage((value) => value + 1) }} /></>;
}
